import { z } from "zod";
import { completeJson } from "./llm";
import { db } from "./db";
import { lookupGstRate } from "./gst-lookup";
import { slugify } from "./slug";
import type { CategoryTemplate } from "./schemas";

/**
 * LLM-drafted category templates — never auto-published.
 *
 * `draftCategoryTemplate` asks gpt-4o to research a category and emit the
 * editorial fields a template needs (composition, origin probabilities, cost
 * bands, sources). Code then:
 *
 *   1. Looks up GST from CBIC (overrides whatever the LLM guessed)
 *   2. Derives keywords + slug deterministically
 *   3. Lands the result in `CategoryDraft.status = "pending"` for human review
 *
 * Nothing reaches the live `Category` table until a maintainer approves the
 * draft via the admin queue. That's the whole "never auto-publish" promise.
 *
 * Costs one gpt-4o call per draft (~$0.02–0.05). Honors `LLM_MONTHLY_USD_CAP`.
 */

// Loose draft shape — flat enough for OpenAI json_object mode (no strict
// nested optionals). Code maps this into the full CategoryTemplate.
const DraftSchema = z.object({
  displayName: z.string(),
  description: z.string(),
  hsnCodes: z.array(z.string()).min(1).max(8),
  defaultGstRate: z.number(),
  typicalStructure: z.object({
    rawMaterials: z.object({ lowPct: z.number(), highPct: z.number() }),
    packaging: z.object({ lowPct: z.number(), highPct: z.number() }),
    manufacturing: z.object({ lowPct: z.number(), highPct: z.number() }),
    logistics: z.object({ lowPct: z.number(), highPct: z.number() }),
    retailMargin: z.object({ lowPct: z.number(), highPct: z.number() }),
    brandMargin: z.object({ lowPct: z.number(), highPct: z.number() }),
    advertising: z.object({ lowPct: z.number(), highPct: z.number() }),
    gst: z.object({ lowPct: z.number(), highPct: z.number() }),
    brandProfit: z.object({ lowPct: z.number(), highPct: z.number() }),
  }),
  rawMaterials: z
    .array(
      z.object({
        name: z.string(),
        sharePctLow: z.number(),
        sharePctHigh: z.number(),
        origins: z.array(
          z.object({
            country: z.string(), // ISO-2 or "MIXED"
            countryName: z.string(),
            probabilityPct: z.number(),
            notes: z.string().optional(),
          }),
        ),
      }),
    )
    .min(2)
    .max(8),
  keywords: z.array(z.string()).min(3).max(30),
  sources: z
    .array(
      z.object({
        title: z.string(),
        url: z.string().url(),
        relevance: z.string(),
      }),
    )
    .min(2)
    .max(8),
});

export type Draft = z.infer<typeof DraftSchema>;

export interface GenerateInput {
  /** Example product that triggered the draft (e.g. "Lay's Magic Masala 52g"). */
  exampleQuery: string;
  /** Hint for the category name (e.g. "potato chips"). Optional. */
  categoryHint?: string;
}

export async function draftCategoryTemplate(
  input: GenerateInput,
): Promise<{ draftId: string; template: CategoryTemplate }> {
  const draft = await completeJson({
    purpose: "draft-category",
    tier: "smart",
    schema: DraftSchema,
    system: SYSTEM_PROMPT,
    user: userPrompt(input),
  });

  const slug = slugify(
    input.categoryHint ?? draft.displayName,
  ).replace(/-/g, "_");

  // CBIC overrides whatever the LLM guessed for GST.
  const primaryHsn = draft.hsnCodes[0]!;
  const gst = await lookupGstRate(primaryHsn, {
    ratePct: draft.defaultGstRate,
  });

  // Build the full CategoryTemplate from the draft + code-derived fields.
  const template: CategoryTemplate = {
    slug,
    displayName: draft.displayName,
    templateVersion: "0.0.1-draft",
    defaultGstRate: gst.ratePct,
    hsnCodes: draft.hsnCodes,
    keywords: draft.keywords.map((k) => k.toLowerCase()),
    typicalStructure: {
      ...draft.typicalStructure,
      gst: {
        lowPct: gst.ratePct,
        highPct: gst.ratePct,
      },
    },
    rawMaterials: draft.rawMaterials.map((rm) => ({
      name: rm.name,
      sharePct: { low: rm.sharePctLow, high: rm.sharePctHigh },
      typicalOrigin: rm.origins,
    })),
    madeInIndiaBand: { lowPct: 0, highPct: 100 }, // informational; not used by compute
    llmGuidance:
      "Draft generated by gpt-4o. Awaiting human review — every number unverified.",
    sources: draft.sources,
  };

  const row = await db.categoryDraft.create({
    data: {
      slug,
      displayName: draft.displayName,
      templateJson: JSON.stringify(template),
      generatedBy: process.env.LLM_MODEL_SMART ?? "gpt-4o",
      exampleQuery: input.exampleQuery,
      status: "pending",
    },
  });

  return { draftId: row.id, template };
}

/**
 * Promote a pending draft into the live `Category` table. Idempotent on slug.
 * Marks the draft as approved.
 */
export async function approveDraft(
  draftId: string,
  reviewerNotes?: string,
): Promise<{ slug: string }> {
  const draft = await db.categoryDraft.findUniqueOrThrow({
    where: { id: draftId },
  });
  if (draft.status !== "pending") {
    throw new Error(`Draft ${draftId} is not pending (status=${draft.status}).`);
  }
  const template = JSON.parse(draft.templateJson) as CategoryTemplate;

  const data = {
    displayName: template.displayName,
    hsnCodes: JSON.stringify(template.hsnCodes),
    keywords: JSON.stringify(template.keywords ?? []),
    defaultGstRate: template.defaultGstRate,
    templateJson: JSON.stringify(template),
    sourcesJson: JSON.stringify(template.sources),
  };
  await db.category.upsert({
    where: { slug: template.slug },
    update: data,
    create: { slug: template.slug, ...data },
  });

  await db.categoryDraft.update({
    where: { id: draftId },
    data: {
      status: "approved",
      reviewedAt: new Date(),
      reviewerNotes,
    },
  });

  return { slug: template.slug };
}

export async function rejectDraft(
  draftId: string,
  reviewerNotes?: string,
): Promise<void> {
  await db.categoryDraft.update({
    where: { id: draftId },
    data: {
      status: "rejected",
      reviewedAt: new Date(),
      reviewerNotes,
    },
  });
}

// ── Prompts ──────────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are an analyst building Parakhi, an open-source Indian product transparency tool. Your job: draft a category template (cost bands, raw materials, origins) for a category we haven't researched yet.

Rules:
- All percentage shares are % of MRP (cost-structure buckets) or % of raw-material composition (rawMaterials.sharePct).
- typicalStructure buckets together should approximately span 100% with GST.
- rawMaterials: list 3–6 typical inputs by composition weight, each with an origin distribution that sums to ~100%. Use ISO-2 country codes (or "MIXED" for genuine unknown).
- Origin probabilities should reflect actual import patterns for India (e.g. palm oil mostly from Indonesia + Malaysia; aluminium cans from Middle East; specialty chemicals from China).
- Cite real public sources (CBIC, company filings, MCA, industry reports, trade data). Do not invent URLs you are not confident exist.
- Keywords: include category-level terms AND specific brand names that fall in this category.
- This is a DRAFT for human review. Be honest about uncertainty in the relevance text of sources.

Return strict JSON matching the schema described in the user message.`;

function userPrompt(input: GenerateInput): string {
  return `Example product: "${input.exampleQuery}"
${input.categoryHint ? `Category hint: ${input.categoryHint}` : ""}

Return JSON with these top-level keys:
  displayName: string (e.g. "Potato Chips & Namkeen")
  description: string (one sentence)
  hsnCodes: string[] (1–8 HSN codes that apply)
  defaultGstRate: number (e.g. 18)
  typicalStructure: {
    rawMaterials, packaging, manufacturing, logistics, retailMargin,
    brandMargin, advertising, gst, brandProfit
  } — each with { lowPct, highPct } as % of MRP
  rawMaterials: [{ name, sharePctLow, sharePctHigh, origins: [{ country, countryName, probabilityPct, notes? }] }]
  keywords: string[] (5–20 lowercase tokens for fuzzy categorization)
  sources: [{ title, url, relevance }] (2–6 real citations)

Be conservative. Numbers will be reviewed by a human before going live.`;
}
